const express = require("express");
const router = express.Router();
const BannerController = require("../Controllers/Banner_Controller");
const About_Controller = require("../Controllers/About_Controller");
const Category_Controller = require("../Controllers/CategoryController");
const CampusController = require("../Controllers/CampusController");
const AdmissionController = require("../Controllers/AddmissionController");
const Concerns_Controller = require("../Controllers/ConcernsController");
const Alumni_Controller = require("../Controllers/AlumniController");
const Courses_Controller = require("../Controllers/CoursesController");
const Be_DevPlus_Controller = require("../Controllers/Be_DevplusController");
const Footer_Controller = require("../Controllers/FooterController");

router.post("/add_banner", BannerController.add_Banner);
router.get("/get_banner", BannerController.get_Banner);
router.post("/add_about", About_Controller.add_About);
router.get("/get_about", About_Controller.get_About);
router.post("/add_category", Category_Controller.add_Category);
router.get("/get_category   ", Category_Controller.get_Category);
router.post("/add_campus", CampusController.add_Campus);
router.get("/get_campus   ", CampusController.get_Campus);
router.post("/add_admission", AdmissionController.add_Admisstion);
router.get("/get_admission", AdmissionController.get_Admisstion);
router.post("/add_concerns", Concerns_Controller.add_Concerns);
router.get("/get_concerns", Concerns_Controller.get_Concerns);
router.post("/add_alumni", Alumni_Controller.add_Alumni);
router.get("/get_alumni", Alumni_Controller.get_Alumni);
router.post("/add_courses", Courses_Controller.add_Courses);
router.get("/get_courses", Courses_Controller.get_Courses);
router.post("/add_be_devPlus", Be_DevPlus_Controller.add_be_devplus);
router.get("/get_be_devPlus", Be_DevPlus_Controller.get_be_devplus);
router.post("/addFooter", Footer_Controller.add_Footer);
router.get("/getFooter", Footer_Controller.get_Footer);
module.exports = router;
